package com.wurtzitane.gregoriusdrugworkspersistence.recipe;

import com.wurtzitane.gregoriusdrugworkspersistence.Tags;
import com.wurtzitane.gregoriusdrugworkspersistence.recipe.materials.LSDChainMaterials;
import com.wurtzitane.gregoriusdrugworkspersistence.recipe.materials.MethamphetamineChainMaterials;
import com.wurtzitane.gregoriusdrugworkspersistence.recipe.materials.SalvinorinChainMaterials;
import com.wurtzitane.gregoriusdrugworkspersistence.worldgen.GregoriusDrugworksOreBuilder;
import gregtech.api.unification.material.Material;
import gregtech.api.util.GTUtility;
import net.minecraft.util.ResourceLocation;

public final class GregoriusDrugworksMaterials {
    private GregoriusDrugworksMaterials() {}

    public static void init() {
        GregoriusDrugworksBaseMaterials.init();
        SalvinorinChainMaterials.init();
        MethamphetamineChainMaterials.init();
        LSDChainMaterials.init();
        MultiblockCasingsMaterials.init();
    }

    public static void materialChanges() {
        GregoriusDrugworksMatProperties.propertyChanges();
        GregoriusDrugworksMatProperties.flagChanges();
        GregoriusDrugworksMatProperties.miscChanges();
        GregoriusDrugworksOreBuilder.registerPendingWorldgen();
    }

    public static ResourceLocation resLoc(String path) {
        return new ResourceLocation(Tags.MOD_ID,
                GTUtility.toLowerCaseUnderscore(GTUtility.lowerUnderscoreToUpperCamel(path)));
    }

    public static Material CeramicFiber;
    public static Material HighTemperatureInsulation;
    public static Material Hexafluoropropylene;
    public static Material PerfluoroalkoxyPolymerSlurry;
    public static Material FluoropolymerStructuralFilm;
    public static Material FluoropolymerResidue;
    public static Material PhthalicAnhydride;
    public static Material TrimelliticAnhydride;
    public static Material PyromelliticDianhydride;
    public static Material Oxydianiline;
    public static Material MPhenylenediamine;
    public static Material BisphenolADianhydride;
    public static Material Polyetherimide;
    public static Material PolyimideSolution;
    public static Material MicroporousPolyimideMembrane;
    public static Material Polysiloxane;
    public static Material IronPentacarbonyl;
    public static Material AsGrownMultiwalledCarbonNanotubes;
    public static Material PurifiedMultiwalledCarbonNanotubes;
    public static Material MDinitrobenzene;
    public static Material PChloronitrobenzene;
    public static Material PNitrophenol;
    public static Material DinitrodiphenylEther44;
    public static Material PhenolicResin;
    public static Material CarbonMatrixComposite;
    public static Material MoltenVolcanicGlass;
    public static Material ObsidianCeramicComposite;
    public static Material AluminosilicateGel;
    public static Material ZeoliteCatalystMatrix;
    public static Material CatalyticCrackingMatrix;
    public static Material HydrogenBromide;
    public static Material HydrogenChloride;
    public static Material HydrogenFluoride;
    public static Material EthyleneOxide;
    public static Material Acetylene;
    public static Material Chloroethane;
    public static Material Material14Butanediol;
    public static Material Material1Hexene;
    public static Material Material2Ethyl2Methyl13Dioxolane;
    public static Material PToluenesulfonicAcid;
    public static Material Material2Methyl2Butene;
    public static Material Material3Bromofuran;
    public static Material Material4MethoxybenzylChloride;
    public static Material Material5AqueousAcetone;
    public static Material Acetaldehyde;
    public static Material AcidicWastewater;
    public static Material Aminopyridine;
    public static Material AmmoniumChlorideSolution;
    public static Material Anisole;
    public static Material Borane;
    public static Material BoraneThf;
    public static Material BoricAcid;
    public static Material Brine;
    public static Material Butanol;
    public static Material Butanone;
    public static Material ButylChloride;
    public static Material ChloroaceticAcid;
    public static Material Chloromethylsilane;
    public static Material Chlorotrimethylsilane;
    public static Material CpbaToluene;
    public static Material WashedCpbaToluene;
    public static Material CrudePyridine;
    public static Material CrudePyridineSolution;
    public static Material Cyclohexylamine;
    public static Material Diad;
    public static Material Dichloromethane;
    public static Material DiethylEther;
    public static Material EthylAcetate;
    public static Material Dimethylformamide;
    public static Material LithiumBromide;
    public static Material EthylChloride;
    public static Material EthylIodoacetate;
    public static Material EthyleneGlycol;
    public static Material Furan;
    public static Material Furfural;
    public static Material HemicelluloseSlurry;
    public static Material Hexane;
    public static Material Hmds;
    public static Material IodoaceticAcid;
    public static Material Isobutane;
    public static Material Isobutanol;
    public static Material Isobutylene;
    public static Material Isopropanol;
    public static Material MchlorobenzoicAcid;
    public static Material MchloroperoxybenzoicAcid;
    public static Material MethoxybenzylAlcohol;
    public static Material Methylbromide;
    public static Material Methylchloride;
    public static Material Nahmds;
    public static Material Thf;
    public static Material Nahmdsinthf;
    public static Material Pentane;
    public static Material PentoseSolution;
    public static Material PhosphorusTrichloride;
    public static Material Pyridine;
    public static Material PyridineOrganicResidue;
    public static Material PyridineResidue;
    public static Material PyridineSaltWasteSlurry;
    public static Material PyridineTreatedWater;
    public static Material PyridineWasteBrine;
    public static Material PyridineWasteSludge;
    public static Material PyridineWasteWater;
    public static Material PyridineWaterAzeotrope;
    public static Material SalAWasteWaterE5ToE6And7;
    public static Material SalAHeavyOrganicResidueE5ToE6And7;
    public static Material SalAOrganicResidueE5ToE6And7;
    public static Material SalATreatedWaterE5ToE6And7;
    public static Material SalAWasteSludgeE5ToE6And7;
    public static Material SalAAnisoleWasteFluid17To172;
    public static Material SalACrudeOrganics102To11;
    public static Material SalAAcidicAcqueousLayerD6ToD8;
    public static Material SalAMixedSaltsSolutionD8ToB9;
    public static Material SalAMixedSaltsSolution102To11;
    public static Material SalACrudeOrganicResidueD8ToB9;
    public static Material SalAMotherLiquorE4ToA5;
    public static Material SalAHeavyOrganicResidue14To15And16;
    public static Material SalAEnonePrecursor;
    public static Material SalAHeavyAromaticResidue;
    public static Material SalAHeavyAromaticResidue17To172;
    public static Material SalATerpeneLikeKetoneCore;
    public static Material SalATriphenylLikeAromatics;
    public static Material SalAContaminatedWasteWaterD8ToB9;
    public static Material SiliconTetrachloride;
    public static Material SodiumAluminateSolution;
    public static Material SodiumBromideBrine;
    public static Material SodiumDichromateSolution;
    public static Material SodiumHydroxideSolution;
    public static Material SodiumMethoxide;
    public static Material SodiumSilicateSolution;
    public static Material SulfurylChloride;
    public static Material TBuliInPentane;
    public static Material Tbscl;
    public static Material Tertbutylchloride;
    public static Material Tertbutyldimethylsilanol;
    public static Material Tescl;
    public static Material ThionylChloride;
    public static Material Tributylamine;
    public static Material Triethylamine;
    public static Material Triethylsilanol;
    public static Material ZeoliteAGel;
    public static Material SodiumBicarbonateSolution;
    public static Material StabilizedCarrierSolution;
    public static Material StabilizedCarrierSolutionWarmed;
    public static Material KappaResetConcentrate;
    public static Material Material2DeacetoxysalvinorinA;
    public static Material Material2EpiSalvinorinB;
    public static Material PyridineHydrochloride;
    public static Material Alumina;
    public static Material PotassiumFluoride;
    public static Material ChromiumOxide;
    public static Material AluminiumHydroxide;
    public static Material CalciumSulfate;
    public static Material CellulosePulp;
    public static Material LigninResidue;
    public static Material Material14Benzoquinone;
    public static Material LithiumHydride;
    public static Material LithiumAluminiumHydride;
    public static Material Dcc;
    public static Material Ddq;
    public static Material DdqReduced;
    public static Material Dicyclohexylurea;
    public static Material PyridiniumChlorochromate;
    public static Material PyridiniumDichromate;
    public static Material PyridiniumSaltWaste;
    public static Material Dmap;
    public static Material Humins;
    public static Material MethylTriphenylPhosphoniumBromide;
    public static Material SalAHydrazinedicarboxylateWaste;
    public static Material SalAAlcohol102;
    public static Material SalAAlcohol112;
    public static Material SalAAlcohol132;
    public static Material SalAAlcohol172;
    public static Material SalAAlcohol5;
    public static Material SalAAldehyde14;
    public static Material SalAAldehydeBaseWaste113To12;
    public static Material SalAReducedIntermediateSlurryB9ToD10;
    public static Material SalABisaldehyde113;
    public static Material SalABisaldehyde12;
    public static Material SalABisolefin9;
    public static Material SalACarboxylicAcid173;
    public static Material SalAChromiumOxidationOrganicWaste112To113;
    public static Material SalASilylationOrganicWasteB9ToD10;
    public static Material SalASilylationOrganicWasteD10To102;
    public static Material SalADiketone8;
    public static Material SalADiol10;
    public static Material SalADioxolane6;
    public static Material SalAOrganicWaste102To11;
    public static Material SalAOrganicWasteE5ToE6And7;
    public static Material SalAEnone4;
    public static Material SalAEnone5;
    public static Material SalAEster7;
    public static Material SalAExomethylene11;
    public static Material SalAFurylAlcohol15;
    public static Material SalAFurylAlcohol16;
    public static Material SalAFurylOrganicWaste14To15And16;
    public static Material SalAHydroborationOrganicWaste11To112;
    public static Material SalAKetal13;
    public static Material SalALactol17;
    public static Material SalAOrganoboraneIntermediate11To112;
    public static Material SalAPdc132To14;
    public static Material SalATbs102;
    public static Material SalATes19;
    public static Material SalASpiroKetoneCarboxylateIntermediate;
    public static Material SalAWittigOrganicWasteD8ToB9;
    public static Material SalAMixedSalts102To11;
    public static Material SalAMixedSaltsD8ToB9;
    public static Material SalvinorinA;
    public static Material SiliconDioxide;
    public static Material MolecularSieve4A;
    public static Material MagnesiumOxide;
    public static Material VanadiumPentoxide;
    public static Material SodiumAcetate;
    public static Material SodiumBorate;
    public static Material SodiumBromide;
    public static Material SodiumChloride;
    public static Material SodiumHydride;
    public static Material SodiumSulfate;
    public static Material SodiumSulfateHydrated;
    public static Material Tbacl;
    public static Material Tbaf;
    public static Material Tbsf;
    public static Material TriethylammoniumChloride;
    public static Material Triphenylphosphine;
    public static Material TriphenylphosphineOxide;
    public static Material LithiumIodide;
    public static Material CalciumCarbide;
    public static Material ActivatedCarbon;
    public static Material AluminiumTrichloride;
    public static Material CalciumHydroxide;
    public static Material Fluorite;
    public static Material Formaldehyde;
    public static Material HydrogenCyanide;
    public static Material HydrogenPeroxide;
    public static Material PotassiumChloride;
    public static Material PotassiumHydroxide;
    public static Material PotassiumIodide;
    public static Material PotassiumCarbonate;
    public static Material Methamphetamine;
    public static Material Chloroacetone;
    public static Material Methylamine;
    public static Material Phenylacetone;
    public static Material LithiumChloride;
    public static Material LSD;
    public static Material AcidifiedSaltWater;
    public static Material TreatedSaltWater;
    public static Material HydrobromicAcid;
    public static Material ParaNitrotoluene;
    public static Material Material2Bromo4Nitrotoluene;
    public static Material Material3Bromo4Methylaniline;
    public static Material Material3Bromo4MethylbenzenediazoniumChloride;
    public static Material Material2Bromotoluene;
    public static Material MixedBromonitrotolueneIsomers;
    public static Material Material2Bromo3Nitrotoluene;
    public static Material NickelOxide;
    public static Material MaterialH2SO4TreatedCarbon;
    public static Material MaleicAnhydride;
    public static Material MaleicAcid;
    public static Material SuccinicAcid;
    public static Material AluminiumNitrate;
    public static Material Pyrolidine;
    public static Material DimethylformamideDimethylAcetal;
    public static Material PyrolidineMixture;
    public static Material SolvatedPyrolidineMixture;
    public static Material Isopropyl;
    public static Material DiisopropylEther;
    public static Material NNDimethyl22Bromo6NitrophenylEthenylamine;
    public static Material TitaniumTrichloride;
    public static Material AmmoniumAcetate;
    public static Material AmmoniumCarbonate;
    public static Material TiCl3AmmoniumAcetateMixture;
    public static Material MagnesiumSulfate;
    public static Material LSDOrganicMixture;
    public static Material LSDCentrifugedOrganicMixture;
    public static Material LSDCombinedOrganicExtract;
    public static Material Material4BromoindoleContainingOil;
    public static Material Material4Bromoindole;
    public static Material ChromatographyPurifyingMixture;
    public static Material LysergicAcid;
    public static Material Diethylamine;
    public static Material SyntheticLSD;
    public static Material CopperOxide;
    public static Material Copper2Chloride;
    public static Material Palladium2Chloride;
    public static Material PolymerizedAcetaldehyde;
    public static Material CalciumCarbonate;
    public static Material Paraldehyde;
    public static Material Material5Ethyl2MethylpyridineCondensate;
    public static Material Material5Ethyl2Methylpyridine;
    public static Material CupricNitrate;
    public static Material CopperDiisocinchomeronate;
    public static Material IsocinchomeronicAcid;
    public static Material BromineVapor;
}
